# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('user_location', models.CharField(blank=True, max_length=60, null=True)),
                ('login_time', models.TimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('confirm_email', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=60, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
