# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180623_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsystem',
            name='user_login_time',
        ),
    ]
