# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_loginsystem_user_login_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, max_length=60, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
